"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.l=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ea,fa;_.p=function(a){return void 0!==a};ea=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};fa=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.r=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Pc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.ha=function(a,b){a=a.split(".");var c=_.l;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.p(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};_.ia=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.t=function(a,b,c){_.t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ea;return _.t.apply(null,arguments)};
_.ja=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ka=function(a){return"function"==_.ga(a)};_.la=function(a){return"number"==typeof a};_.u=function(a){return"string"==typeof a};_.ma=function(a){var b=_.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.na=function(a){return"array"==_.ga(a)};_.oa=function(){};_.pa=function(a){a=a.split(".");for(var b=_.l,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
var qa=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};qa.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var sa=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};_.ta=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ta);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.ta,Error);_.ta.prototype.name="CustomError";var ua;_.va=function(a){return function(){return a}}(!1);_.wa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;var xa,ya,Aa,za,Da,Ea,Ca;xa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};ya=function(a){a=String(a);if(xa(a))try{return eval("("+a+")")}catch(b){}throw Error("b`"+a);};_.Ba=function(a,b){var c=[];za(new Aa(b),a,c);return c.join("")};
Aa=function(a){this.a=a};
za=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.na(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],za(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),Ca(d,c),c.push(":"),za(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":Ca(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("c`"+typeof b);}}};Da={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Ea=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; Ca=function(a,b){b.push('"',a.replace(Ea,function(a){var b=Da[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Da[a]=b);return b}),'"')};
var Ga,Ha,Ia,Ka;_.Fa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ga=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};Ha=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Ia=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.Ja=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Ka="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.La=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Ma=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Na=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Oa=function(a){Oa[" "](a);return a};Oa[" "]=_.oa;_.Pa=function(a,b){try{return Oa(a[b]),!0}catch(c){}return!1};_.Qa=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var Ra=function(){};var Va,Xa,Ya,Za,$a,ab,bb,Wa,db,fb;_.Sa=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ta=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ua=function(a){return/^[\s\xa0]*$/.test(a)};Va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.cb=function(a){if(!Wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace($a,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ab,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(bb,"&#0;"));return a};Xa=/&/g;Ya=/</g;Za=/>/g;$a=/"/g;ab=/'/g;bb=/\x00/g;Wa=/[\x00&<>"']/;db=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.eb=function(a){return null==a?"":String(a)};
_.gb=function(a,b){var c=0;a=Va(String(a)).split(".");b=Va(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=fb(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||fb(0==f[2].length,0==h[2].length)||fb(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; fb=function(a,b){return a<b?-1:a>b?1:0};
_.w=function(){this.G=this.G;this.B=this.B};_.w.prototype.G=!1;_.w.prototype.$=function(){this.G||(this.G=!0,this.v())};_.z=function(a,b){_.x(a,_.ia(_.y,b))};_.x=function(a,b,c){a.G?_.p(c)?b.call(c):b():(a.B||(a.B=[]),a.B.push(_.p(c)?(0,_.t)(b,c):b))};_.w.prototype.v=function(){if(this.B)for(;this.B.length;)this.B.shift()()};_.y=function(a){a&&"function"==typeof a.$&&a.$()};
var hb="closure_listenable_"+(1E6*Math.random()|0),ib=function(a){return!(!a||!a[hb])},jb=0;a:{var lb=_.l.navigator;if(lb){var mb=lb.userAgent;if(mb){_.kb=mb;break a}}_.kb=""}_.A=function(a){return-1!=_.kb.indexOf(a)};var nb=function(){};nb.prototype.a=null;var pb=function(a){var b;(b=a.a)||(b={},ob(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var rb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("e");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,q,v,P){if("%"==q)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("f");arguments[0]=e;return qb[q].apply(null,arguments)})},qb={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+db(" ",Number(c)-a.length):db(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+db(" ",a):f+db(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return qb.f((0,window.parseInt)(a,10),b, c,d,0,f,h,k)}};qb.i=qb.d;qb.u=qb.d;
_.B=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=rb("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+rb(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+rb.apply({},c)))};
var sb=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};sb.prototype.setVersion=function(a){this.c=a;return this};sb.prototype.Ma=function(a){this.a=a;return this};sb.prototype.nb=function(a){this.g=_.Ja(a);return this};var tb;tb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.C=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ub=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.u(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};_.vb=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.wb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.yb=function(a,b){b=_.xb(a,b,void 0);return 0>b?null:_.u(a)?a.charAt(b):a[b]};_.xb=function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.zb=function(a,b){return 0<=tb(a,b)};_.Bb=function(a,b){b=tb(a,b);var c;(c=0<=b)&&_.Ab(a,b);return c};
_.Ab=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Cb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.Db=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Eb=function(){this.b=this.a=null},Gb=new qa(function(){return new Fb},function(a){a.reset()},100);Eb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Fb=function(){this.next=this.b=this.a=null};Fb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Fb.prototype.reset=function(){this.next=this.b=this.a=null};
var Kb;_.Hb=[];_.Ib=[];_.Jb=!1;Kb=function(a){_.Hb[_.Hb.length]=a;if(_.Jb)for(var b=0;b<_.Ib.length;b++)a((0,_.t)(_.Ib[b].b,_.Ib[b]))};_.Mb=function(a,b){this.type="undefined"!=typeof _.Lb&&a instanceof _.Lb?String(a):a;this.b=this.target=b;this.c=!1;this.xb=!0};_.Mb.prototype.l=function(){this.c=!0};_.Mb.prototype.g=function(){this.xb=!1};var Nb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.La=e;this.key=++jb;this.removed=this.Ha=!1},Ob=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.La=null};var Pb;Pb=function(){return _.A("iPhone")&&!_.A("iPod")&&!_.A("iPad")};_.Qb=function(){return _.A("Macintosh")};_.Rb=function(){return _.A("Windows")};_.Sb=function(){return _.A("CrOS")};var Tb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Ub=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}}};
var Vb=function(a,b){_.Mb.call(this,a,b);this.U=b};_.r(Vb,_.Mb);var Wb=function(a){_.w.call(this);this.a=a;this.h=!1};_.r(Wb,_.w);Wb.prototype.setEnabled=function(a){this.h=a};var Xb=function(a){this.src=a;this.a={};this.b=0},Zb=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var k=Yb(b,c,e,f);-1<k?(a=b[k],d||(a.Ha=!1)):(a=new Nb(c,a.src,h,!!e,f),a.Ha=d,b.push(a));return a};Xb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Yb(e,b,c,d);return-1<b?(Ob(e[b]),_.Ab(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var $b=function(a,b){var c=b.type;c in a.a&&_.Bb(a.a[c],b)&&(Ob(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Xb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Ob(d[e]);delete this.a[c];this.b--}return b};
var ac=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Yb(a,c,d,e));return-1<b?a[b]:null},bc=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return Ga(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})},Yb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.La==d)return e}return-1};
var cc=function(){return(_.A("Chrome")||_.A("CriOS"))&&!_.A("Edge")};var dc,ec=function(){};_.r(ec,nb);var fc=function(a){return(a=ob(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},ob=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("i");}return a.b};dc=new ec;
_.gc=function(a){if(a.R&&"function"==typeof a.R)return a.R();if(_.u(a))return a.split("");if(_.ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};
_.hc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ma(a)||_.u(a))(0,_.C)(a,b,void 0);else{var c;if(a.W&&"function"==typeof a.W)c=a.W();else if(a.R&&"function"==typeof a.R)c=void 0;else if(_.ma(a)||_.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=Ia(a);for(var d=_.gc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var ic,kc,lc,jc;ic=function(a){_.l.setTimeout(function(){throw a;},0)};_.mc=function(a,b){var c=a;b&&(c=(0,_.t)(a,b));c=jc(c);!_.ka(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.A("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(kc||(kc=lc()),kc(c)):_.l.setImmediate(c)};
lc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.A("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.A("Trident")&&!_.A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.tb;c.tb=null;a()}};return function(a){d.next={tb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};jc=function(a){return a};Kb(function(a){jc=a});
_.oc=function(){this.a="";this.g=_.nc;this.b=null};_.oc.prototype.jb=!0;_.oc.prototype.Ja=function(){return this.b};_.oc.prototype.kb=!0;_.oc.prototype.ib=function(){return this.a};_.nc={};_.pc=function(a,b){var c=new _.oc;c.a=a;c.b=b;return c};_.pc("<!DOCTYPE html>",0);_.pc("",0);_.qc=_.pc("<br>",0);
var rc="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},sc=function(){};sc.prototype.next=function(){throw rc;};sc.prototype.ga=function(){return this};
var tc=function(a){if(a instanceof sc)return a;if("function"==typeof a.ga)return a.ga(!1);if(_.ma(a)){var b=0,c=new sc;c.next=function(){for(;;){if(b>=a.length)throw rc;if(b in a)return a[b++];b++}};return c}throw Error("j");},uc=function(a,b){if(_.ma(a))try{(0,_.C)(a,b,void 0)}catch(c){if(c!==rc)throw c;}else{a=tc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==rc)throw c;}}},vc=function(a){if(_.ma(a))return _.Db(a);a=tc(a);var b=[];uc(a,function(a){b.push(a)});return b};
var wc,xc,Ac,Ec,Fc,Jc,Kc,Mc;wc=_.A("Opera");_.D=_.A("Trident")||_.A("MSIE");xc=_.A("Edge");_.yc=_.A("Gecko")&&!(-1!=_.kb.toLowerCase().indexOf("webkit")&&!_.A("Edge"))&&!(_.A("Trident")||_.A("MSIE"))&&!_.A("Edge");_.zc=-1!=_.kb.toLowerCase().indexOf("webkit")&&!_.A("Edge");Ac=_.l.navigator||null;_.Bc=Ac&&Ac.platform||"";_.Cc=_.Qb();_.Dc=_.Rb();Ec=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var Gc="",Hc=function(){var a=_.kb;if(_.yc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(xc)return/Edge\/([\d\.]+)/.exec(a);if(_.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.zc)return/WebKit\/(\S+)/.exec(a);if(wc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Hc&&(Gc=Hc?Hc[1]:"");if(_.D){var Ic=Ec();if(null!=Ic&&Ic>(0,window.parseFloat)(Gc)){Fc=String(Ic);break a}}Fc=Gc}Jc=Fc;Kc={};_.Lc=function(a){return _.Qa(Kc,a,function(){return 0<=_.gb(Jc,a)})};var Nc=_.l.document; Mc=Nc&&_.D?Ec()||("CSS1Compat"==Nc.compatMode?(0,window.parseInt)(Jc,10):5):void 0;
var Sc=function(a,b){Oc||Pc();Qc||(Oc(),Qc=!0);var c=Rc,d=Gb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Oc,Pc=function(){if(-1!=String(_.l.Promise).indexOf("[native code]")){var a=_.l.Promise.resolve(void 0);Oc=function(){a.then(Tc)}}else Oc=function(){_.mc(Tc)}},Qc=!1,Rc=new Eb,Tc=function(){for(var a;a=Rc.remove();){try{a.a.call(a.b)}catch(b){ic(b)}sa(Gb,a)}Qc=!1};
var Uc=!_.D||9<=Number(Mc);!_.yc&&!_.D||_.D&&9<=Number(Mc)||_.yc&&_.Lc("1.9.1");_.D&&_.Lc("9");var Vc=!_.D||9<=Number(Mc),Wc=_.D&&!_.Lc("9");!_.zc||_.Lc("528");_.yc&&_.Lc("1.9b")||_.D&&_.Lc("8")||wc&&_.Lc("9.5")||_.zc&&_.Lc("528");_.yc&&!_.Lc("8")||_.D&&_.Lc("9");var Xc=function(){};_.r(Xc,Ra);Xc.prototype.clear=function(){var a=vc(this.ga(!0)),b=this;(0,_.C)(a,function(a){b.remove(a)})};_.E=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("d");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.E?(c=a.W(),d=a.R()):(c=Ia(a),d=Ha(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.E.prototype.R=function(){Yc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.E.prototype.W=function(){Yc(this);return this.a.concat()};_.$c=function(a,b){return Zc(a.b,b)};
_.E.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.E.prototype.remove=function(a){return Zc(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&Yc(this),!0):!1};var Yc=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Zc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Zc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.E.prototype.get=function(a,b){return Zc(this.b,a)?this.b[a]:b};
_.E.prototype.set=function(a,b){Zc(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.E.prototype.forEach=function(a,b){for(var c=this.W(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.E.prototype.ga=function(a){Yc(this);var b=0,c=this.c,d=this,e=new sc;e.next=function(){if(c!=d.c)throw Error("k");if(b>=d.a.length)throw rc;var e=d.a[b++];return a?e:d.b[e]};return e};var Zc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var ad=_.A("Firefox"),bd=Pb()||_.A("iPod"),cd=_.A("iPad"),dd=_.A("Android")&&!(cc()||_.A("Firefox")||_.A("Opera")||_.A("Silk")),ed=cc(),fd=_.A("Safari")&&!(cc()||_.A("Coast")||_.A("Opera")||_.A("Edge")||_.A("Silk")||_.A("Android"))&&!(Pb()||_.A("iPad")||_.A("iPod"));
var gd=null;var md,pd,od;_.jd=function(a){return a?new _.hd(_.id(a)):ua||(ua=new _.hd)};_.ld=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.kd(window.document,"*",a,b)[0];return d||null};
_.kd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.zb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.nd=function(a,b){_.Fa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:md.hasOwnProperty(d)?a.setAttribute(md[d],b):_.Sa(d,"aria-")||_.Sa(d,"data-")?a.setAttribute(d,b):a[d]=b})};md={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
pd=function(a,b,c){function d(c){c&&b.appendChild(_.u(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.ma(f)||_.ja(f)&&0<f.nodeType?d(f):(0,_.C)(od(f)?_.Db(f):f,d)}};_.qd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.id=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};od=function(a){if(a&&"number"==typeof a.length){if(_.ja(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ka(a))return"function"==typeof a.item}return!1};
_.hd=function(a){this.a=a||_.l.document||window.document};_.g=_.hd.prototype;_.g.wa=_.jd;_.g.C=function(a){return _.u(a)?this.a.getElementById(a):a};
_.g.ka=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Uc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.cb(h.name),'"');if(h.type){f.push(' type="',_.cb(h.type),'"');var k={};_.La(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.u(h)?f.className=h:_.na(h)?f.className=h.join(" "):_.nd(f,h));2<e.length&&pd(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var rd=function(a,b){_.Mb.call(this,a?a.type:"");this.b=this.target=null;this.keyCode=0;this.B=this.m=this.h=this.j=!1;this.a=this.state=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.b=b,(b=a.relatedTarget)&&_.yc&&_.Pa(b,"nodeName"),this.keyCode=a.keyCode||0,this.j=a.ctrlKey,this.h=a.altKey,this.m=a.shiftKey,this.B=a.metaKey,this.state=a.state,this.a=a,a.defaultPrevented&&this.g())};_.r(rd,_.Mb);
rd.prototype.l=function(){rd.A.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};rd.prototype.g=function(){rd.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Wc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var ud,vd,wd,Bd,Fd,Gd,Ed,Cd;_.td=function(a,b){this.a=0;this.B=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.oa)try{var c=this;a.call(b,function(a){_.sd(c,2,a)},function(a){_.sd(c,3,a)})}catch(d){_.sd(this,3,d)}};ud=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};ud.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};vd=new qa(function(){return new ud},function(a){a.reset()},100);wd=function(a,b,c){var d=vd.get();d.h=a;d.b=b;d.c=c;return d};
_.yd=function(){var a,b=new _.td(function(b){a=b});return new xd(b,a)};_.td.prototype.then=function(a,b,c){return _.zd(this,_.ka(a)?a:null,_.ka(b)?b:null,c)};Ma(_.td);_.td.prototype.cancel=function(a){0==this.a&&Sc(function(){var b=new Ad(a);Bd(this,b)},this)};
Bd=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?Bd(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):Cd(c),Dd(c,e,3,b)))}a.g=null}else _.sd(a,3,b)};Fd=function(a,b){a.b||2!=a.a&&3!=a.a||Ed(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.zd=function(a,b,c,d){var e=wd(null,null,null);e.a=new _.td(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.p(e)&&b instanceof Ad?h(b):a(e)}catch(q){h(q)}}:h});e.a.g=a;Fd(a,e);return e.a};_.td.prototype.m=function(a){this.a=0;_.sd(this,2,a)};_.td.prototype.o=function(a){this.a=0;_.sd(this,3,a)};
_.sd=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.m,h=a.o;if(e instanceof _.td)Fd(e,wd(f||_.oa,h||null,a)),d=!0;else if(Na(e))e.then(f,h,a),d=!0;else{if(_.ja(e))try{var k=e.then;if(_.ka(k)){Gd(e,k,f,h,a);d=!0;break a}}catch(n){h.call(a,n);d=!0;break a}d=!1}}d||(a.B=c,a.a=b,a.g=null,Ed(a),3!=b||c instanceof Ad||Hd(a,c))}};
Gd=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};Ed=function(a){a.j||(a.j=!0,Sc(a.l,a))};Cd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.td.prototype.l=function(){for(var a;a=Cd(this);)Dd(this,a,this.a,this.B);this.j=!1};
var Dd=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,Id(b,c,d);else try{b.g?b.h.call(b.c):Id(b,c,d)}catch(e){Jd.call(null,e)}sa(vd,b)},Id=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},Hd=function(a,b){a.h=!0;Sc(function(){a.h&&Jd.call(null,b)})},Jd=ic,Ad=function(a){_.ta.call(this,a)};_.r(Ad,_.ta);Ad.prototype.name="cancel";var xd=function(a,b){this.a=a;this.b=b};
var Kd=function(a){this.a=a};_.r(Kd,Xc);_.g=Kd.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.u(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ga=function(a){var b=0,c=this.a,d=new sc;d.next=function(){if(b>=c.length)throw rc;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.u(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var Ld,Md,Nd,Qd,Sd,ae,Td,Vd,Ud,Yd,Wd,Rd,be;_.F=function(a,b){this.b=this.B=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;a instanceof _.F?(this.j=_.p(b)?b:a.j,Ld(this,a.h),this.B=a.B,this.b=a.b,Md(this,a.c),this.a=a.a,Nd(this,Od(a.g)),_.Pd(this,a.l)):a&&(c=String(a).match(Tb))?(this.j=!!b,Ld(this,c[1]||"",!0),this.B=Qd(c[2]||""),this.b=Qd(c[3]||"",!0),Md(this,c[4]),this.a=Qd(c[5]||"",!0),Nd(this,c[6]||"",!0),_.Pd(this,c[7]||"",!0)):(this.j=!!b,this.g=new Rd(null,0,this.j))};
_.F.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Sd(b,Td,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.B)&&a.push(Sd(b,Td,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Sd(c,"/"==c.charAt(0)?Ud:Vd,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Sd(c,Wd));return a.join("")};
Ld=function(a,b,c){a.h=c?Qd(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};Md=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("l`"+b);a.c=b}else a.c=null};Nd=function(a,b,c){b instanceof Rd?(a.g=b,Xd(a.g,a.j)):(c||(b=Sd(b,Yd)),a.g=new Rd(b,0,a.j))};_.G=function(a,b,c){a.g.set(b,c)};_.Pd=function(a,b,c){a.l=c?Qd(b):b};_.Zd=function(a){return a instanceof _.F?new _.F(a):new _.F(a,void 0)};
_.$d=function(a,b){a instanceof _.F||(a=_.Zd(a));b instanceof _.F||(b=_.Zd(b));var c=a;a=new _.F(c);var d=!!b.h;d?Ld(a,b.h):d=!!b.B;d?a.B=b.B:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)Md(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var c=_.Sa(e,"/"),e=e.split("/"),f=[],h=0;h<e.length;){var k=e[h++];"."==k?c&&h==e.length&&f.push(""):".."==k?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(k),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?Nd(a,Od(b.g)):d=!!b.l;d&&_.Pd(a,b.l);return a};Qd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};Sd=function(a,b,c){return _.u(a)?(a=(0,window.encodeURI)(a).replace(b,ae),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};ae=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
Td=/[#\/\?@]/g;Vd=/[\#\?:]/g;Ud=/[\#\?]/g;Yd=/[\#\?@]/g;Wd=/#/g;Rd=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};be=function(a){a.a||(a.a=new _.E,a.b=0,a.g&&Ub(a.g,function(b,c){b=(0,window.decodeURIComponent)(b.replace(/\+/g," "));be(a);a.g=null;b=ce(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};Rd.prototype.remove=function(a){be(this);a=ce(this,a);return _.$c(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
Rd.prototype.clear=function(){this.a=this.g=null;this.b=0};var de=function(a,b){be(a);b=ce(a,b);return _.$c(a.a,b)};Rd.prototype.W=function(){be(this);for(var a=this.a.R(),b=this.a.W(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Rd.prototype.R=function(a){be(this);var b=[];if(_.u(a))de(this,a)&&(b=_.Cb(b,this.a.get(ce(this,a))));else{a=this.a.R();for(var c=0;c<a.length;c++)b=_.Cb(b,a[c])}return b};
Rd.prototype.set=function(a,b){be(this);this.g=null;a=ce(this,a);de(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};Rd.prototype.get=function(a,b){a=a?this.R(a):[];return 0<a.length?String(a[0]):b};_.ee=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(ce(a,b),_.Db(c)),a.b+=c.length)};
Rd.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.W(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.R(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")};
var Od=function(a){var b=new Rd;b.g=a.g;a.a&&(b.a=new _.E(a.a),b.b=a.b);return b},ce=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Xd=function(a,b){b&&!a.c&&(be(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.ee(this,c,a))},a));a.c=b};
var fe;fe=function(a){return(a=a.exec(_.kb))?a[1]:""};_.ge=function(){if(ad)return fe(/Firefox\/([0-9.]+)/);if(_.D||xc||wc)return Jc;if(ed)return fe(/Chrome\/([0-9.]+)/);if(fd&&!(Pb()||_.A("iPad")||_.A("iPod")))return fe(/Version\/([0-9.]+)/);if(bd||cd){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.kb);if(a)return a[1]+"."+a[2]}else if(dd)return(a=fe(/Android\s+([0-9.]+)/))?a:fe(/Version\/([0-9.]+)/);return""}();
var je,le,me,pe;_.H=function(){};_.he="function"==typeof window.Uint8Array;_.I=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.na(c)&&!(_.he&&c instanceof window.Uint8Array))){a.B=b-a.h;a.c=c;break a}a.B=Number.MAX_VALUE}a.m={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.B?(c+=a.h,a.g[c]=a.g[c]||_.ie):a.c[c]=a.c[c]||_.ie;e&&e.length&&(0,_.C)(e,_.ia(je,a))};_.ie=[];
_.J=function(a,b){if(b<a.B){b+=a.h;var c=a.g[b];return c===_.ie?a.g[b]=[]:c}c=a.c[b];return c===_.ie?a.c[b]=[]:c};_.ke=function(a,b,c){a=_.J(a,b);return null==a?c:a};_.K=function(a,b,c){b<a.B?a.g[b+a.h]=c:a.c[b]=c};je=function(a,b){var c,d;(0,_.C)(b,function(b){var e=_.J(a,b);null!=e&&(c=b,d=e,_.K(a,b,void 0))});return c?(_.K(a,c,d),c):0};_.L=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.J(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.N=function(a,b,c){a.b||(a.b={});var d=c?_.M(c):c;a.b[b]=c;_.K(a,b,d)};le=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.na(c))for(var d=0;d<c.length;d++)c[d]&&_.M(c[d]);else c&&_.M(c)}};_.M=function(a){le(a);return a.g};me=_.l.JSON&&_.l.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.H.prototype.j=_.he?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!gd){gd={};for(var a=0;65>a;a++)gd[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=gd,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;n||(q=64,h||(k=64));b.push(a[v],a[f],a[k],a[q])}return b.join("")};try{var b=me.call(null,_.M(this),
ne)}finally{window.Uint8Array.prototype.toJSON=a}return b}:me?function(){return me.call(null,_.M(this),ne)}:function(){return _.Ba(_.M(this),ne)};var ne=function(a,b){if(_.la(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.H.prototype.toString=function(){le(this);return this.g.toString()};pe=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.oe(a[d],b[d]))return!1;return!0};
_.oe=function(a,b){if(a==b)return!0;if(!_.ja(a)||!_.ja(b)||a.constructor!=b.constructor)return!1;if(_.he&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],k=b[c];h&&h.constructor==Object&&(d=h,h=void 0);k&&k.constructor==Object&&(e=k,k=void 0);if(!_.oe(h,k))return!1}return d||e?(d=d||{},e=e||{},pe(d,e)):!0}if(a.constructor=== Object)return pe(a,b);throw Error("n");};
var qe,re,se,ve,xe,Ee,ye,Ge,Fe,ze,we,He,ue;qe="closure_lm_"+(1E6*Math.random()|0);re={};se=0;_.te=function(a,b,c,d,e){if(_.na(b)){for(var f=0;f<b.length;f++)_.te(a,b[f],c,d,e);return null}c=ue(c);return ib(a)?a.listen(b,c,d,e):ve(a,b,c,!1,d,e)};
ve=function(a,b,c,d,e,f){if(!b)throw Error("o");var h=!!e,k=we(a);k||(a[qe]=k=new Xb(a));c=Zb(k,b,c,d,e,f);if(c.proxy)return c;d=xe();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ye(b.toString()),d);else throw Error("p");se++;return c};xe=function(){var a=ze,b=Vc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Ae=function(a,b,c,d,e){if(_.na(b)){for(var f=0;f<b.length;f++)_.Ae(a,b[f],c,d,e);return null}c=ue(c);return ib(a)?a.Ka(b,c,d,e):ve(a,b,c,!0,d,e)};_.De=function(a,b,c,d,e){if(_.na(b))for(var f=0;f<b.length;f++)_.De(a,b[f],c,d,e);else c=ue(c),ib(a)?a.Oa(b,c,d,e):a&&(a=we(a))&&(b=ac(a,b,c,!!d,e))&&Ee(b)};
Ee=function(a){if(!_.la(a)&&a&&!a.removed){var b=a.src;if(ib(b))$b(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(ye(c),d);se--;(c=we(b))?($b(c,a),0==c.b&&(c.src=null,b[qe]=null)):Ob(a)}}};ye=function(a){return a in re?re[a]:re[a]="on"+a};Ge=function(a,b,c,d){var e=!0;if(a=we(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Fe(f,d),e=e&&!1!==f)}return e};
Fe=function(a,b){var c=a.listener,d=a.La||a.src;a.Ha&&Ee(a);return c.call(d,b)};
ze=function(a,b){if(a.removed)return!0;if(!Vc){var c=b||_.pa("window.event");b=new rd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=Ge(c[e],a,!0,b),d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=Ge(c[e],a,!1,b),d=d&&f}return d}return Fe(a,new rd(b,this))}; we=function(a){a=a[qe];return a instanceof Xb?a:null};He="__closure_events_fn_"+(1E9*Math.random()>>>0);ue=function(a){if(_.ka(a))return a;a[He]||(a[He]=function(b){return a.handleEvent(b)});return a[He]};Kb(function(a){ze=a(ze)});
var Ie=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.r(Ie,Kd);/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Je=function(a,b){this.l=[];this.F=a;this.w=b||null;this.j=this.g=!1;this.c=void 0;this.I=this.K=this.o=!1;this.m=0;this.a=null;this.B=0};_.Je.prototype.cancel=function(a){if(this.g)this.c instanceof _.Je&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.B--,0>=b.B&&b.cancel())}this.F?this.F.call(this.w,this):this.I=!0;this.g||this.D(new _.Ke)}};_.Je.prototype.H=function(a,b){this.o=!1;Le(this,a,b)};
var Le=function(a,b,c){a.g=!0;a.c=c;a.j=!b;Me(a)},Oe=function(a){if(a.g){if(!a.I)throw new Ne;a.I=!1}};_.Je.prototype.b=function(a){Oe(this);Le(this,!0,a)};_.Je.prototype.D=function(a){Oe(this);Le(this,!1,a)};_.Qe=function(a,b,c){_.Pe(a,b,null,c)};_.Pe=function(a,b,c,d){a.l.push([b,c,d]);a.g&&Me(a)};_.Je.prototype.then=function(a,b,c){var d,e,f=new _.td(function(a,b){d=a;e=b});_.Pe(this,d,function(a){a instanceof _.Ke?f.cancel():e(a)});return f.then(a,b,c)};Ma(_.Je);
_.Je.prototype.h=function(a){var b=new _.Je;_.Pe(this,b.b,b.D,b);a&&(b.a=this,this.B++);return b};
var Re=function(a){return(0,_.wb)(a.l,function(a){return _.ka(a[1])})},Me=function(a){if(a.m&&a.g&&Re(a)){var b=a.m,c=Se[b];c&&(_.l.clearTimeout(c.a),delete Se[b]);a.m=0}a.a&&(a.a.B--,delete a.a);for(var b=a.c,d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var k=f.call(e||a.w,b);_.p(k)&&(a.j=a.j&&(k==b||k instanceof Error),a.c=b=k);if(Na(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.o=!0}catch(n){b=n,a.j=!0,Re(a)||(c=!0)}}a.c=b;d&&(k=(0,_.t)(a.H,
a,!0),d=(0,_.t)(a.H,a,!1),b instanceof _.Je?(_.Pe(b,k,d),b.K=!0):b.then(k,d));c&&(b=new Te(b),Se[b.a]=b,a.m=b.a)},Ne=function(){_.ta.call(this)};_.r(Ne,_.ta);Ne.prototype.message="Deferred has already fired";Ne.prototype.name="AlreadyCalledError";_.Ke=function(){_.ta.call(this)};_.r(_.Ke,_.ta);_.Ke.prototype.message="Deferred was canceled";_.Ke.prototype.name="CanceledError";var Te=function(a){this.a=_.l.setTimeout((0,_.t)(this.g,this),0);this.b=a}; Te.prototype.g=function(){delete Se[this.a];throw this.b;};var Se={};
var Ve;_.O=function(a){_.w.call(this);this.S=a;this.I={}};_.r(_.O,_.w);var Ue=[];_.O.prototype.listen=function(a,b,c,d){_.na(b)||(b&&(Ue[0]=b.toString()),b=Ue);for(var e=0;e<b.length;e++){var f=_.te(a,b[e],c||this.handleEvent,d||!1,this.S||this);if(!f)break;this.I[f.key]=f}return this};_.We=function(a,b,c,d){Ve(a,b,c,d,void 0)};Ve=function(a,b,c,d,e,f){if(_.na(c))for(var h=0;h<c.length;h++)Ve(a,b,c[h],d,e,f);else(b=_.Ae(b,c,d||a.handleEvent,e,f||a.S||a))&&(a.I[b.key]=b)};
_.O.prototype.Oa=function(a,b,c,d,e){if(_.na(b))for(var f=0;f<b.length;f++)this.Oa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.S||this,c=ue(c),d=!!d,b=ib(a)?ac(a.g,String(b),c,d,e):a?(a=we(a))?ac(a,b,c,d,e):null:null,b&&(Ee(b),delete this.I[b.key]);return this};_.O.prototype.removeAll=function(){_.Fa(this.I,function(a,b){this.I.hasOwnProperty(b)&&Ee(a)},this);this.I={}};_.O.prototype.v=function(){_.O.A.v.call(this);this.removeAll()};_.O.prototype.handleEvent=function(){throw Error("q");};
_.Q=function(){_.w.call(this);this.g=new Xb(this);this.ba=this;this.I=null};_.r(_.Q,_.w);_.Q.prototype[hb]=!0;_.Q.prototype.H=function(a){this.I=a};_.Q.prototype.removeEventListener=function(a,b,c,d){_.De(this,a,b,c,d)};
_.R=function(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);a=a.ba;d=b.type||b;if(_.u(b))b=new _.Mb(b,a);else if(b instanceof _.Mb)b.target=b.target||a;else{var e=b;b=new _.Mb(d,a);_.La(b,e)}var e=!0,f;if(c)for(var h=c.length-1;!b.c&&0<=h;h--)f=b.b=c[h],e=f.ma(d,!0,b)&&e;b.c||(f=b.b=a,e=f.ma(d,!0,b)&&e,b.c||(e=f.ma(d,!1,b)&&e));if(c)for(h=0;!b.c&&h<c.length;h++)f=b.b=c[h],e=f.ma(d,!1,b)&&e;return e};_.g=_.Q.prototype;_.g.v=function(){_.Q.A.v.call(this);this.g&&this.g.removeAll(void 0);this.I=null};
_.g.listen=function(a,b,c,d){return Zb(this.g,String(a),b,!1,c,d)};_.g.Ka=function(a,b,c,d){return Zb(this.g,String(a),b,!0,c,d)};_.g.Oa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)};_.g.ma=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,k=f.La||f.src;f.Ha&&$b(this.g,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.xb};
_.Xe=function(a,b){_.Q.call(this);this.b=a||1;this.a=b||_.l;this.c=(0,_.t)(this.wc,this);this.h=(0,_.m)()};_.r(_.Xe,_.Q);_.g=_.Xe.prototype;_.g.pa=!1;_.g.X=null;_.g.setInterval=function(a){this.b=a;this.X&&this.pa?(this.stop(),this.start()):this.X&&this.stop()};_.g.wc=function(){if(this.pa){var a=(0,_.m)()-this.h;0<a&&a<.8*this.b?this.X=this.a.setTimeout(this.c,this.b-a):(this.X&&(this.a.clearTimeout(this.X),this.X=null),_.R(this,"tick"),this.pa&&(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)()))}};
_.g.start=function(){this.pa=!0;this.X||(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)())};_.g.stop=function(){this.pa=!1;this.X&&(this.a.clearTimeout(this.X),this.X=null)};_.g.v=function(){_.Xe.A.v.call(this);this.stop();delete this.a};_.Ye=function(a,b,c){if(_.ka(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("r");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.Ze=function(a){_.l.clearTimeout(a)};
var $e=function(a){_.I(this,a,"capi_md1571",null,null)};_.r($e,_.H);$e.messageId="capi_md1571";var af={pb:0,Cc:1,Ac:2,ob:3,$a:4},bf=function(a){_.I(this,a,0,null,null)};_.r(bf,_.H);_.df=function(a){_.I(this,a,"h_exts",cf,null)};_.r(_.df,_.H);var cf=[2];_.df.messageId="h_exts";var ef=function(a){_.Q.call(this);this.headers=new _.E;this.o=a||null;this.b=!1;this.m=this.a=null;this.F="";this.c=this.D=this.h=this.w=!1;this.l=0;this.j=null;this.V="";this.M=this.N=!1},ff,gf,hf,qf,pf,mf,rf;_.r(ef,_.Q);ff=/^https?$/i;gf=["POST","PUT"];hf=[];_.jf=function(a,b,c,d,e,f,h){var k=new ef;hf.push(k);b&&k.listen("complete",b);k.Ka("ready",k.Y);f&&(k.l=Math.max(0,f));h&&(k.N=h);k.send(a,c,d,e)};ef.prototype.Y=function(){this.$();_.Bb(hf,this)};
ef.prototype.send=function(a,b,c,d){if(this.a)throw Error("s`"+this.F+"`"+a);b=b?b.toUpperCase():"GET";this.F=a;this.w=!1;this.b=!0;this.a=this.o?fc(this.o):fc(dc);this.m=this.o?pb(this.o):pb(dc);this.a.onreadystatechange=(0,_.t)(this.T,this);try{this.D=!0,this.a.open(b,String(a),!0),this.D=!1}catch(f){kf(this);return}a=c||"";var e=new _.E(this.headers);d&&_.hc(d,function(a,b){e.set(b,a)});d=_.yb(e.W(),lf);c=_.l.FormData&&a instanceof _.l.FormData;!_.zb(gf,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.V&&(this.a.responseType=this.V);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{mf(this),0<this.l&&((this.M=nf(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.t)(this.S,this)):this.j=_.Ye(this.S,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){kf(this)}};var nf=function(a){return _.D&&_.Lc(9)&&_.la(a.timeout)&&_.p(a.ontimeout)},lf=function(a){return"content-type"==a.toLowerCase()};
ef.prototype.S=function(){"undefined"!=typeof _.aa&&this.a&&(_.R(this,"timeout"),this.abort(8))};var kf=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);of(a);pf(a)},of=function(a){a.w||(a.w=!0,_.R(a,"complete"),_.R(a,"error"))};ef.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.R(this,"complete"),_.R(this,"abort"),pf(this))};ef.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),pf(this,!0));ef.A.v.call(this)};
ef.prototype.T=function(){this.G||(this.D||this.h||this.c?qf(this):this.K())};ef.prototype.K=function(){qf(this)};qf=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=rf(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.Ye(a.T,0,a);else if(_.R(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.sf(a)?(_.R(a,"complete"),_.R(a,"success")):of(a)}finally{pf(a)}}};
pf=function(a,b){if(a.a){mf(a);var c=a.a,d=a.m[0]?_.oa:null;a.a=null;a.m=null;b||_.R(a,"ready");try{c.onreadystatechange=d}catch(e){}}};mf=function(a){a.a&&a.M&&(a.a.ontimeout=null);_.la(a.j)&&(_.Ze(a.j),a.j=null)};
_.sf=function(a){var b=rf(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.F).match(Tb)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!ff.test(a?a.toLowerCase():"");c=b}return c};rf=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Kb(function(a){ef.prototype.K=a(ef.prototype.K)});
var uf=function(){for(var a=10,b=tf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},tf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.vf=function(a){_.I(this,a,0,null,null)};_.r(_.vf,_.H);_.wf=function(a,b){_.w.call(this);this.j=b||uf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.O(this);_.z(this,this.h);this.h.listen(window,"message",this.m)};_.r(_.wf,_.w);_.wf.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.wf.prototype.m=function(a){a=a.a;var b;b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.F(b)).b,b=_.Ta(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.u(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.na(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new $e(c),_.J(c,1)==this.j)){b=_.J(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);
1==_.J(c,2)?this.send(2):this.l(c,a)}}};_.wf.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new $e;_.K(b,3,this.j);_.K(b,1,this.a);_.K(b,2,a);var d=JSON.stringify(_.M(b)),e=this.g,f=this.c;_.D?_.Ye(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var xf=function(a){Wb.call(this,a);this.O=null;this.b=0};_.r(xf,Wb);xf.prototype.yb=function(a){this.O=a;return this};var yf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];xf.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Xe(6E4);_.z(this,a);var b=new _.O(this);_.z(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
xf.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<yf.length;++b)if(this.b==yf[b].age){a=yf[b].name;break}if(""!=a){var b=zf.test(_.kb)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.Zd(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.eb(this.a.a);_.Ua(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ka(this.O)&&this.O(b,a[d].displayName,a[d].value);_.jf("https://clients2.google.com/cr/staging_perf"+c,Af,"POST","",null,6E4,!0)}}};var Af=function(a){_.sf(a.target)},zf=/(x86_64|Win64)/;
var Cf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new Ie);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=ya(a)||[]}catch(c){}a=!1;_.na(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&Bf(this)},Bf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Ba(a.a))}catch(b){}};
var Df=function(a,b,c,d,e){this.g=_.yd();this.a=new _.wf((0,_.t)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.Xe(50);this.b.start();_.te(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=wd(b,b,this);b.g=!0;Fd(a,b)};Df.prototype.j=function(){_.y(this.a);_.De(this.b,"tick",this.c,!1,this);_.y(this.b)};Df.prototype.c=function(){this.a.send(1)};Df.prototype.h=function(a,b){2==_.J(a,2)&&this.g.b(b.origin)};
var Ef=function(a,b,c){_.w.call(this);this.b=a;a=_.J(b,3);b=_.J(b,1);this.a=new _.wf((0,_.t)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.z(this,this.a)};_.r(Ef,_.w);Ef.prototype.send=function(a){var b=new $e;_.N(b,4,a);this.a.send(af.pb,b)};Ef.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send(af.ob)};Ef.prototype.g=function(a){_.J(a,2)==af.pb&&(a=_.L(a,bf,4),this.b(a))};Ef.prototype.c=_.oa;
var Gf=function(a,b,c){_.w.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],Ff(this)):(this.a=new _.wf(_.oa,_.J(b,1)),a=_.J(b,3),this.a.a=a)};_.r(Gf,_.w);Gf.prototype.v=function(){Gf.A.v.call(this);this.b&&this.b.close();_.y(this.a)};Gf.prototype.c=function(){this.g=new _.O(this);_.z(this,this.g);Ff(this)};Gf.prototype.send=function(a){this.b.postMessage(_.M(a))};
Gf.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;Ff(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send(af.$a,void 0,[c]);_.y(d)};var Ff=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};Gf.prototype.j=function(a){a=a.a;var b;try{b=new bf(a.data)}catch(c){return}this.h(b)};
var S=function(a){Wb.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.I=!0;this.j=10;this.b=null;this.c=!1};_.r(S,Wb);S.prototype.Bb=function(a){this.I=a;return this};S.prototype.setUseLocalStorage=S.prototype.Bb;S.prototype.vc=function(a){this.j=Math.min(a,100);return this};S.prototype.setMaxErrorsPerHour=S.prototype.vc;S.prototype.zb=function(a){this.o=a;return this};S.prototype.setGlobalSampling=S.prototype.zb;S.prototype.rb=function(a,b){this.m[a]=b;return this};
S.prototype.addPerErrorMessageSampling=S.prototype.rb;S.prototype.yb=function(a){this.O=a;return this};S.prototype.setCallback=S.prototype.yb;S.prototype.uc=function(a){this.g=a;return this};S.prototype.setClientId=S.prototype.uc;S.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.w.bind(this);this.setEnabled(!0);return!0};S.prototype.enable=S.prototype.enable;
S.prototype.vb=function(a,b,c,d,e){var f=_.Zd(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ka(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var k=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(k=this.m[q])}if(h=(100*Math.random()).toFixed(6)>=this.o*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new Cf(this.j,this.I));if(null===this.b)h=0;else{a:{h=this.b;k=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
Bf(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Ja(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",wc?k="Opera":_.D?k="Internet Explorer":ad?k="Firefox":ed?k="Chrome":fd&&(k="Safari"),h.browser=k,h.browser_version=_.ge,h.os=_.Sb()?"Chrome OS":_.A("Linux")?"Linux":_.Rb()?"Windows":_.A("Android")?"Android":Pb()?"iPhone":_.A("iPad")?"iPad":_.A("iPod")?"iPod":_.Qb()?"Mac":"Unknown",k=_.kb,n="",_.Rb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):Pb()||_.A("iPad")||_.A("iPod")?
(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.Qb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.A("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.Sb()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ua(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=Hf(h),e=null!=e?
_.eb(e.stack):"",_.Ua(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),If(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.eb(this.a.a),_.Ua(a)||(f.version=a),If(this,"https://clients2.google.com/cr/staging_perf",Hf(f)))};S.prototype.reportError=S.prototype.vb;S.prototype.w=function(a,b,c,d,e){this.vb(a,b,c,d,e);null!=this.l&&_.ka(this.l)&&this.l(a,b,c,d,e)};
var Hf=function(a){var b="",c;for(c in a)b+=_.Ua(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},If=function(a,b,c,d){d=d||"";var e=_.Ua(d)?{}:{"Content-Type":"text/plain"};_.jf(b+c,a.H.bind(a,b),"POST",d,e,6E4,!0)};S.prototype.H=function(a,b){_.sf(b.target)};
var Jf=function(a,b,c){var d=!1;_.p(_.J(b,2))?_.J(b,2)==af.$a&&(d=!0):d=ed;return d?new Gf(a,b,c):new Ef(a,b,c)};var Kf=function(a){_.w.call(this);this.b=new sb(a);this.a={}};_.r(Kf,_.w);_.ha("webmonitoring.Monitoring",Kf);Kf.prototype.setVersion=function(a){this.b.setVersion(a);return this};Kf.prototype.setVersion=Kf.prototype.setVersion;Kf.prototype.Ma=function(a){this.b.Ma(a);return this};Kf.prototype.setChannel=Kf.prototype.Ma;Kf.prototype.nb=function(a){this.b.nb(a);return this};Kf.prototype.setContext=Kf.prototype.nb;Kf.prototype.Ia=function(){null!=this.a[2]||(this.a[2]=new S(this.b));return this.a[2]}; Kf.prototype.createJsErrorsReporter=Kf.prototype.Ia;
var Pf,Rf;_.Lf=function(){_.Q.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.x(this,this.o,this);this.b=null};_.r(_.Lf,_.Q);_.Lf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.Nf=function(a){a.o();a.h=[];a.b=new _.Je;a.c.push((0,_.t)(a.b.cancel,a.b));a.l=!1;_.Qe(a.b.h(),function(a){(bc(this.g)||this.I)&&_.Mf(this);this.c.push(_.ia(_.y,a))},a)};_.Lf.prototype.sendMessage=function(a){Of(this,_.M(a))};var Of=function(a,b){if(a.b){var c=new bf;_.K(c,1,b);_.Qe(a.b.h(),function(a){a.send(c)})}};
_.Lf.prototype.J=function(){return this};_.Lf.prototype.ca=function(a,b,c){this.a.ca(a,b,c)};_.Qf=function(a,b,c,d){_.Nf(a);Pf(a,b,c,d).then(function(a){var d=new $e;_.K(d,1,a.xc);_.K(d,3,c);d=Jf((0,_.t)(this.m,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};Pf=function(a,b,c,d){var e=uf();b=(new Df("*",b,c,e,d)).g.a;a.c.push((0,_.t)(b.cancel,b));return b.then(function(a){return{xc:e,origin:a}})};
_.Lf.prototype.D=function(a,b){if(_.J(a,2)==af.ob||_.J(a,2)==af.$a)_.y(this.a),this.a=null,this.b.b(Jf((0,_.t)(this.m,this),a,b))};_.Lf.prototype.m=function(a){this.h.push(a);this.w()};_.Lf.prototype.w=function(){for(;Rf(this););};Rf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.J(a.h.shift(),1);a.j&&Of(a.j,b);_.R(a,new Vb(b[0],b));return!0};_.Mf=function(a){a.l||(a.l=!0,a.b&&_.Qe(a.b.h(),function(a){a.c();_.Ye(this.w,0,this)},a))}; _.Lf.prototype.listen=function(a,b,c,d){_.Mf(this);return _.Lf.A.listen.call(this,a,b,c,d)};_.Lf.prototype.Ka=function(a,b,c,d){_.Mf(this);return _.Lf.A.Ka.call(this,a,b,c,d)};_.Lf.prototype.H=function(a){_.Mf(this);return _.Lf.A.H.call(this,a)};
var Sf=function(a){Kf.call(this,a)};_.r(Sf,Kf);Sf.prototype.Ia=function(){var a=Sf.A.Ia.call(this);a.c=!0;return a};_.Tf=function(){var a=new Sf("Google_Hangouts_Chrome");a.Ma(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new xf(a.b));a.a[1].enable();a.Ia().Bb(!1).zb(100).rb("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
try{
var gp=function(a,b){a.j=b;_.x(a,function(){this.j=null},a);_.Mf(a)},hp=function(a){_.I(this,a,"uv_r_hrd",null,null)};_.r(hp,_.H);hp.messageId="uv_r_hrd";
var ip=function(a,b){return a.g.get(b)},jp=function(a,b){_.zd(a,null,b,void 0)},kp=function(a){var b=new _.Lf;_.Nf(b);b.a=new _.wf((0,_.t)(b.D,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.ia(_.y,b.a));return b},lp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ma(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};
var mp=function(a){this.a=a||{cookie:""}},np=/\s*;\s*/;_.g=mp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(np),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.W=function(){return op(this).keys};_.g.R=function(){return op(this).values};_.g.clear=function(){for(var a=op(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var op=function(a){a=(a.a.cookie||"").split(np);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var pp=function(){},sp=function(a){var b=a.la,c=function(a){c.A.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Rc||(this.a[d]=new this.Z[d](a))};_.r(c,b);for(var d=[];a;){if(b=a.la){b.Z&&lp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ka(e[f])&&e[f]!==b){var h=!!e[f].Qb,k=qp(f,e,d,h);(h=rp(f,e,k,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.Z=d;return c},qp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},rp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Sb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Rb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]],f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].hc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var q=this.a[c[f]];e.push(q?q[a].apply(q,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Sb||b[a].Rb||b[a].hc? e=null:e=tp;return e},tp=function(){return[]};pp.prototype.j=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var up=function(a){(a?a:function(){}).Qb=!0};
var vp=function(){};_.r(vp,pp);vp.prototype.b=function(a){return a};up(vp.prototype.b);vp.prototype.g=function(){return!0};up(vp.prototype.g);var wp=function(a){return this.hb.j(a)};var xp=function(a){_.I(this,a,"h_cc",null,null)};_.r(xp,_.H);xp.messageId="h_cc";var yp=function(a,b){_.K(a,3,b)},zp=function(a,b){_.K(a,4,b)},Ap=function(a,b){_.K(a,11,b)},Bp=function(a){_.I(this,a,0,null,null)};_.r(Bp,_.H);var Cp=function(a){_.I(this,a,0,null,null)};_.r(Cp,_.H);var Dp=function(a){_.I(this,a,0,null,null)};_.r(Dp,_.H);var Ep=function(a){_.I(this,a,0,null,null)};_.r(Ep,_.H);
var Fp=function(a){_.I(this,a,"ci:ec",null,null)};_.r(Fp,_.H);Fp.messageId="ci:ec";var Gp=function(a){_.I(this,a,0,null,null)};_.r(Gp,_.H);var Hp=function(a,b){var c=new Gp;_.K(c,1,b);_.K(c,2,a);return c},Ip=Hp("?",0),Jp=Hp("q",1),Kp=Hp("<",2),Lp=Hp(">",3),Mp=Hp("~",4),Np=Hp("s",5),Op={Bc:Ip,Kc:Jp,Ec:Kp,Fc:Lp,Dc:Mp,Mc:Np};var Pp=function(a){var b=_.$d(_.J(a,2),"/webchat/extension-start");_.J(a,5)&&_.G(b,"e",_.J(a,5));return new _.td(function(a,d){_.jf(b,function(b){_.sf(b.target)||d();try{var c;var e=b.target;try{c=e.a?e.a.responseText:""}catch(n){c=""}var k=JSON.parse(c);a(new _.df(k))}catch(n){d(n.message)}})})};
var Qp=function(a,b,c){if(!this.hb){for(var d=this.constructor;d&&!d.la;)d=d.A&&d.A.constructor;d.la.ub||(d.la.ub=sp(d));this.hb=new d.la.ub(this);this.j||(this.j=wp)}var e=this.hb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Sa(e,"https://talkgadget.google.com/talkgadget/")){var d=(new mp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.zb(f,d)&&h.test(d)&&(e=_.Zd(e),
e=_.Zd("https://"+d+e.a).toString())}this.g=e;this.c=c||new Fp;a.notificationsOnly&&_.K(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=ip(new _.F(window.location.href),"authuser"),null!=c&&(this.b=c));this.o=a.clientUrl||"notifierclient";c=ip(_.Zd(this.o),"authuser");null!=c&&(this.b=c);this.Pa=a.propertyName||"Google Talk";this.H=a.cssUrl;this.locale=a.locale;this.l=a.debug;this.Ga=a.userJid;this.Da=a.uiVersion;this.bc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.ba=a.hostLogMinValue;
this.va=a.hideChat;this.Ub=a.refresh;this.N=a.hideProfileCard;this.V=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.S=a.hideRecentConversations;this.M=a.hideOTR;this.fb=a.hostServerMessageCallback||!1;this.fa=a.isCentralRoster;this.Tb=a.isFullFrame||!1;this.$b=a.rosterClass||"talk_roster";this.cc=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ua=a.parentToken;
this.Zb=b||!1;this.h=_.p(a.isRtl)?a.isRtl:_.wa.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in Op)b.push(_.M(Op[k]))}this.D=a.entityId;this.Ea=a.useQuasarPanels||!1;this.Ba=a.silent||!1;this.gb=a.ignoreCentralRoster||!1;this.Wb=a.lazy||!1;this.bb=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.m=a.screen;this.w=a.docsConfig;this.Vb=a.jsmode;this.ta=a.moleWidth;this.sa=a.moleHeight;this.ra=a.minimizedMoleHeight||36;this.dc=a.derp;this.Ca=window.location.protocol+
"//"+window.location.host;this.B="";this.K=a.optOutAllowed;this.F=a.legacyTalkSignedIn;this.Fa=a.useSpareMole;this.I=a.conversationId};vp.A||_.r(vp,pp);Qp.la=vp;
var Sp=function(a){var b={},c=_.ke(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.J(a,2)&&27!=_.J(a,2)&&(d="http://"));-1!=c.indexOf("talkgadget.")?(b.clientBaseUrl=d+c+"/talkgadget/_/",b.clientUrl="chat"):(b.clientBaseUrl=d+c+"/webchat/u/"+_.ke(a,8,"0")+"/",b.clientUrl="load");b.authUser=_.ke(a,8,"0");b.propertyName=Rp(_.J(a,2));b.locale=_.J(a,4);b.hideProfileCard=!0;b.parentToken=_.J(a,3);b.isRtl=_.ke(a,6,!1);b.lazy=_.ke(a,7,!1);b.entityId=_.J(a,9);b.hostSettings=
_.J(a,5);b.jsmode=_.J(a,11);b.isFullFrame=_.ke(a,13,!1);b.rosterId=_.ke(a,12,"talk_roster");b.rosterIframeIdB=_.ke(a,15,"gtn-roster-iframe-id-b");b.derp=!!_.ke(a,16,!1);c=_.L(a,Ep,14);null!=c&&(b.isCentralRoster=_.ke(c,1,!1),b.useQuasarPanels=_.ke(c,2,!1));c=_.L(a,Bp,10);null!=c&&(b.moleManagerLeftMargin=_.J(c,1),b.moleManagerMiddleMargin=_.J(c,2),b.moleManagerRightMargin=_.J(c,3),b.moleManagerNoMoleAreaMargin=_.J(c,4),b.moleManagerBoundingElementId=_.J(c,5),b.moleWidth=_.J(c,6),b.moleHeight=_.J(c,
7),b.minimizedMoleHeight=_.J(c,8));c=_.L(a,Cp,18);null!=c&&(b.optOutAllowed=_.ke(c,1,!0),d=_.L(c,Dp,3),null!=d&&(b.legacyTalkSignedIn=_.ke(d,1,!0)),c=_.J(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Fp;_.K(c,2,!0);_.K(c,1,!0);_.K(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=_.ke(a,17,!1);b.conversationId=_.J(a,19);return b},Rp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";
case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},Tp=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Zd(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var Up=function(a){this.a=a;_.D||(delete this.a.lpu,delete this.a.ppu)},Vp=["cn","tp"],Wp=function(a,b){var c;if(_.ka(window.document.postMessage)||_.ka(window.postMessage)||_.D&&window.postMessage)c=1;else if(_.yc)c=2;else{var d;if(d=_.D){d=!1;try{c=window.opener,window.opener={},d=_.Pa(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Up(d)};_.ha("GTalk_IFrameChannelConfig.build",Wp);
var Xp=function(a,b,c,d,e){_.w.call(this);this.a=a;this.b=d||window.document;this.g=new _.O(this);_.z(this,this.g);var f=_.kb;d=new _.F(a.g+a.o);_.ke(a.c,2,!1)||(_.G(d,"ts","0"),_.G(d,"re",a.bc),_.G(d,"ref",a.Ub));_.G(d,"client","sm");_.G(d,"prop",a.Pa);_.G(d,"nav","true");_.G(d,"fid",a.a);a.l&&_.G(d,"debug",a.l);_.G(d,"os",_.Bc);_.G(d,"stime",c);a.va&&_.G(d,"hc",a.va);for(c=0;c<Vp.length;++c);b=_.Ba(b.a);_.G(d,"xpc",b);_.G(d,"ec",_.Ba(_.M(a.c)));a.m&&_.G(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.G(d,
"ua",f);a.ua&&_.G(d,"pvt",a.ua);a.fb&&_.G(d,"hsmc","true");_.p(a.ba)&&_.G(d,"logl",a.ba);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.G(d,"href",b.join("?")));b=new _.F(window.location.href);"false"==ip(b,"uacheck")&&_.G(d,"uacheck",!1);(f=a.Vb)&&_.G(d,"jsmode",f);(f=ip(b,"cssmode"))&&_.G(d,"cssmode",f);(f=ip(b,"convid"))&&_.G(d,"convid",f);if(f=b.g.R("convp"))_.na(f)||(f=[String(f)]),_.ee(d.g,"convp",f);(f=ip(b,"smexp"))&&_.G(d,
"smexp",f);f=b.g.R("mods");a.Wb&&f.push("lazy");e&&(f=_.Cb(f,e));0<f.length&&_.G(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=ip(b,"authuser"))?_.G(d,"authuser",e):null!=a.b&&_.G(d,"authuser",a.b);e=ip(b,"eid");_.Ua(_.eb(e))||_.G(d,"eid",e);_.Ua(_.eb(this.a.D))||_.G(d,"eid",this.a.D);null!=this.a.position&&_.G(d,"pos",this.a.position);_.p(a.Da)&&_.G(d,"uiv",this.a.Da);a.H&&_.G(d,"css",a.H);e=a.locale||ip(b,"hl");null!=e&&_.G(d,"hl",e);_.p(a.Ga)&&_.G(d,"uj",a.Ga);null!=a.N&&_.G(d,"hpc",a.N);
null!=a.V&&_.G(d,"hsm",a.V);null!=a.T&&_.G(d,"hro",a.T);null!=a.S&&_.G(d,"hrc",a.S);null!=a.M&&_.G(d,"hotr",a.M);null!=a.fa&&_.G(d,"pop",a.fa);a.Zb&&_.G(d,"pal","1");null!=a.Ea&&_.G(d,"uqp",a.Ea);null!=a.K&&_.G(d,"gooa",a.K);null!=a.F&&_.G(d,"gltsi",a.F);null!=a.Fa&&_.G(d,"gusm",a.Fa);null!=a.Ba&&_.G(d,"sl",a.Ba);a.gb&&_.G(d,"icr","1");a.bb&&_.G(d,"hpl","1");a.Y&&_.G(d,"hs",a.Y);a.w&&_.G(d,"dc",_.Ba(_.M(a.w)));null!=a.ta&&_.G(d,"molew",a.ta);null!=a.sa&&_.G(d,"moleh",a.sa);null!=a.ra&&_.G(d,"mmoleh",
a.ra);a.dc&&_.G(d,"derp","1");a.B&&_.G(d,"fcho",a.B);null!=a.Ca&&_.G(d,"two",a.Ca);null!=a.I&&_.G(d,"convid",a.I);_.G(d,"host","1");_.G(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36));this.c=d.toString()};_.r(Xp,_.w);
var Yp=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.$b,a.b.body.appendChild(e));a=(0,_.t)(function(){var a="";this.a.Tb||(a="height:400px");var b=this.b.createElement("iframe");_.nd(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.ld("talk_loading_msg",e)||_.qd(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.We(this.g,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});k.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var $p=function(){var a=this;_.O.call(this);_.B("Starting ...");this.listen(window,"unload",this.$);this.b=new _.vf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));this.a=kp(_.J(this.b,1));_.z(this,this.a);this.g=new _.Lf;_.z(this,this.g);jp(Pp(this.b).then(function(b){return Zp(a,b)}),function(a){_.B("Failed to start : %s.",a||"")})},aq;_.r($p,_.O);
var Zp=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.J(b,1))){var c=new xp,d=_.Zd(_.J(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.K(c,1,e);_.K(c,2,27);_.K(c,13,!0);_.K(c,17,!0);yp(c,_.J(b,1));Ap(c,_.J(a.b,4));zp(c,_.J(a.b,3)||"en");b=Sp(c);var f=new Qp(b,!0,b.endpointConfig);f.g=Tp(f.g,f.b);f.B=window.location.origin;b=Wp(f.g,f.a);b=new Xp(f,b,(0,_.m)(),window.document);_.z(a,b);Yp(b,f.cc,function(){},function(){_.Qf(a.g,window.document.getElementById(f.a).contentWindow,"31ACFC0_","google.com");gp(a.g, a.a);gp(a.a,a.g);a.a.sendMessage(new hp)})}};_.ha("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Tf();if(!aq||aq.G)aq=new $p;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
